article_module/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.ArticlesListView.as_view(), name='articles_page'),
    path('cat/<str:category>', views.ArticlesListView.as_view(), name='articles_by_categories_list')

]

eshop_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('home_module.urls')),
    path('', include('account_module.urls')),
    path('products/', include('product_module.urls')),
    path('contact-us/', include('contact_module.urls')),
    path('articles/', include('article_module.urls')),
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home_module/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.HomeView.as_view(), name='home_page'),
    path('about-us', views.AboutView.as_view(), name='about_page'),
    path('contact-us', views.contact_page)
]

article_module/models.py
from django.db import models

from account_module.models import User


# Create your models here.

class ArticleCategory(models.Model):
    parent = models.ForeignKey('ArticleCategory',
                               null=True,
                               blank=True,
                               on_delete=models.CASCADE,
                               verbose_name='دسته بندی والد')
    title = models.CharField(max_length=200, verbose_name='عنوان دسته بندی')
    url_title = models.CharField(max_length=200, verbose_name='url عنوان مقاله در')
    is_active = models.BooleanField(default=True, verbose_name='فعال / غیرفعال ')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = 'دسته بندی های مقالات'
        verbose_name = 'دسته بندی مقالات'


class Article(models.Model):
    title = models.CharField(max_length=300, verbose_name='عنوان مقاله')
    slug = models.SlugField(max_length=400, db_index=True, allow_unicode=True, verbose_name='url عنوان مقاله در')
    image = models.ImageField(upload_to='images/articles', verbose_name='تصویر مقاله')
    short_description = models.TextField(verbose_name='توضیح کوتاه')
    text = models.TextField(verbose_name='توضیح اصلی')
    is_active = models.BooleanField(default=True, verbose_name='فعال / غیرفعال ')
    selected_categories = models.ManyToManyField(ArticleCategory, verbose_name='دسته بندی ها')
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='نویسنده مقاله', null=True, editable=False)
    created_date = models.DateTimeField(auto_now_add=True, editable=False, verbose_name='تاریخ ثبت')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = 'مقالات'
        verbose_name = 'مقاله'

article_module/views.py
from django.http import HttpRequest
from django.shortcuts import render
from django.views.generic.list import ListView

from article_module.models import Article, ArticleCategory


# Create your views here.


class ArticlesListView(ListView):
    template_name = 'article_module/articles_list.html'
    model = Article
    paginate_by = 5

    def get_context_data(self,  *args, **kwargs):
        context = super(ArticlesListView, self).get_context_data(*args, **kwargs)
        return context

    def get_queryset(self):
        query = super(ArticlesListView, self).get_queryset()
        category_name = self.kwargs.get('category')
        if category_name is not None:
            query = query.filter(selected_categories__url_title__iexact=category_name)
            return query


def article_categories_component(request: HttpRequest):
    article_main_categories = ArticleCategory.objects.filter(is_active=True, parent_id=None)
    context = {
        'main_categories': article_main_categories,

    }
    return render(request, 'article_module/component/article_categories_component.html', context)

article_module/templates/article_module/component/article_categories_component.html
<div class="panel-group category-products" id="accordian"><!--category-productsr-->

    {% for main_category in main_categories %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    {% if main_category.articlecategory_set.all %}
                        <a data-toggle="collapse" data-parent="#accordian" href="#{{ main_category.url_title }}">
                            <span class="badge pull-right"><i class="fa fa-plus"></i></span>
                            {{ main_category.title }}
                        </a>
                    {% else %}
                        <a href="#sportswear">
                            {{ main_category.title }}
                        </a>
                    {% endif %}

                </h4>
            </div>

            {% if main_category.articlecategory_set.all %}
                <div id="{{ main_category.url_title }}" class="panel-collapse collapse">
                    <div class="panel-body">
                        <ul>
                            {% for sub_category in main_category.articlecategory_set.all %}
                                <li><a href="">{{ sub_category.title }}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>

            {% endif %}
            {#            {% if main_category.articlecategory_set.all %}#}
            {#            {% endif %}#}


        </div>
    {% endfor %}
</div><!--/category-productsr-->